/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    dividends: Dividend;
    stocks: Stock;
    users: User;
  };
  globals: {};
}
export interface Dividend {
  id: string;
  stock: string | Stock;
  quarter?: string;
  dividend: number;
  date: string;
  xdate?: string;
  createdAt: string;
  updatedAt: string;
}
export interface Stock {
  id: string;
  name: string;
  hebrewName?: string;
  symbol: string;
  ISIN?: string;
  issuerId?: number;
  securityId?: number;
  PE?: number;
  DPR?: number;
  capital?: number;
  latestPrice?: number;
  historicPrices: {
    date: string;
    price: number;
    id?: string;
  }[];
  dividends: {
    dividend?: string | Dividend;
    id?: string;
  }[];
  createdAt: string;
  updatedAt: string;
}
export interface User {
  id: string;
  username: string;
  lastName?: string;
  roles: ('admin' | 'kid')[];
  accountId?: string;
  birthday?: string;
  portfolioValue?: number;
  balance?: number;
  stocks: {
    stock?: string | Stock;
    quantity?: number;
    dividends: {
      dividend?: string | Dividend;
      quantity?: number;
      id?: string;
    }[];
    id?: string;
  }[];
  transactions: {
    type: 'buy' | 'sell' | 'deposit' | 'withdrawal';
    status?: 'pending' | 'completed';
    sum: number;
    date: string;
    stock?: string | Stock;
    quantity?: number;
    price?: number;
    id?: string;
  }[];
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
