/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    stocks: Stock;
  };
  globals: {};
}
export interface User {
  id: string;
  firstName: string;
  lastName?: string;
  role: 'admin' | 'user';
  userDetails: {
    accountId: string;
    balance?: number;
    stocks: {
      amount: number;
      stockId: string | Stock;
      id?: string;
    }[];
    transactions: {
      type: 'buy' | 'sell' | 'deposit' | 'withdraw';
      sum?: number;
      date: string;
      stock: {
        stockId?: string | Stock;
        amount?: number;
        price?: number;
      };
      id?: string;
    }[];
  };
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Stock {
  id: string;
  name: string;
  marketValue?: number;
  symbol: string;
  historicPrices: {
    date: string;
    price: number;
    id?: string;
  }[];
  createdAt: string;
  updatedAt: string;
}
