/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    stocks: Stock;
    transactions: Transaction;
    dividends: Dividend;
  };
  globals: {};
}
export interface User {
  id: string;
  username: string;
  lastName?: string;
  roles: ('admin' | 'kid')[];
  userDetails: {
    accountId?: string;
    birthday?: string;
    balance?: number;
    stocks: {
      amount?: number;
      stockId?: string | Stock;
      id?: string;
    }[];
    dividends: {
      amount?: number;
      dividendId?: string | Dividend;
      id?: string;
    }[];
  };
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Stock {
  id: string;
  name: string;
  hebrewName?: string;
  marketValue?: number;
  symbol: string;
  historicPrices: {
    date: string;
    price: number;
    id?: string;
  }[];
  dividends?: string[] | Dividend[];
  owners?: string[] | User[];
  createdAt: string;
  updatedAt: string;
}
export interface Dividend {
  id: string;
  quarter: string;
  date: string;
  amount?: number;
  stock?: string | Stock;
  createdAt: string;
  updatedAt: string;
}
export interface Transaction {
  id: string;
  user: string | User;
  type: 'buy' | 'sell' | 'deposit' | 'withdraw';
  sum: number;
  date: string;
  stock: {
    stockId?: string | Stock;
    amount?: number;
    price?: number;
  };
  createdAt: string;
  updatedAt: string;
}
